package middleware

import (
	"fmt"
	"net/http"
	"retargetly-exercise/helpers"
	"strings"

	"github.com/dgrijalva/jwt-go"
)

//ExtractToken get the token from the request Header
func ExtractToken(r *http.Request) string {
	bearToken := r.Header.Get("Authorization")
	//expecting "Authorization": {token}
	strArr := strings.Split(bearToken, " ")
	if len(strArr) == 2 {
		return strArr[1]
	}
	return ""
}

//VerifyToken Verify if the token was generated by the server
func VerifyToken(r *http.Request) (*jwt.Token, error) {
	tokenString := ExtractToken(r)
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		//Make sure that the token method conform to "SigningMethodHMAC"
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(helpers.GetEnvVariable("TOKEN_SECRET_KEY")), nil
	})
	if err != nil {
		return nil, err
	}
	return token, nil
}

//TokenValid Check if the token is (still) valid 
func TokenValid(r *http.Request) error {
	token, err := VerifyToken(r)
	if err != nil {
		return err
	}
	_, ok := token.Claims.(jwt.MapClaims)
	if !ok && !token.Valid {
		return err
	}

	return nil
}
